import {
  Wrench,
  Car,
  Sparkles,
  Monitor,
  Truck,
  GraduationCap,
  HeartHandshake,
  PartyPopper,
  Utensils,
  Briefcase,
  PawPrint,
  Stethoscope,
  LayoutGrid,
} from "lucide-react"
export const serviceCategories = [
  {
    name: "Maison & Bricolage",
    color: "text-sky-900",
    accent: "bg-gradient-to-tr from-sky-600/50 to-sky-400/20",
    icon: Wrench,
  },
  {
    name: "Transport & Véhicules",
    color: "text-slate-900",
    accent: "bg-gradient-to-tr from-slate-500/50 to-slate-300/20",
    icon: Car,
  },
  {
    name: "Nettoyage & Entretien",
    color: "text-cyan-900",
    accent: "bg-gradient-to-tr from-cyan-400/50 to-cyan-200/20",
    icon: Sparkles,
  },
  {
    name: "Digital & Technologie",
    color: "text-indigo-900",
    accent: "bg-gradient-to-tr from-indigo-400/50 to-indigo-200/20",
    icon: Monitor,
  },
  {
    name: "Déménagement & Livraison",
    color: "text-amber-900",
    accent: "bg-gradient-to-tr from-amber-500/50 to-amber-300/20",
    icon: Truck,
  },
  {
    name: "Éducation & Formation",
    color: "text-purple-900",
    accent: "bg-gradient-to-tr from-purple-400/50 to-purple-200/20",
    icon: GraduationCap,
  },
  {
    name: "Services à la personne",
    color: "text-rose-900",
    accent: "bg-gradient-to-tr from-rose-400/50 to-rose-200/20",
    icon: HeartHandshake,
  },
  {
    name: "Événementiel",
    color: "text-fuchsia-900",
    accent: "bg-gradient-to-tr from-fuchsia-400/50 to-fuchsia-200/20",
    icon: PartyPopper,
  },
  {
    name: "Restauration & Cuisine",
    color: "text-orange-900",
    accent: "bg-gradient-to-tr from-orange-500/50 to-orange-300/20",
    icon: Utensils,
  },
  {
    name: "Services professionnels",
    color: "text-blue-900",
    accent: "bg-gradient-to-tr from-blue-400/50 to-blue-200/20",
    icon: Briefcase,
  },
  {
    name: "Animaux",
    color: "text-emerald-900",
    accent: "bg-gradient-to-tr from-emerald-400/50 to-emerald-200/20",
    icon: PawPrint,
  },
  {
    name: "Santé & Bien-être",
    color: "text-teal-900",
    accent: "bg-gradient-to-tr from-teal-400/50 to-teal-200/20",
    icon: Stethoscope,
  },
  {
    name: "Autres",
    color: "text-gray-900",
    accent: "bg-gradient-to-tr from-gray-400/50 to-gray-200/20",
    icon: LayoutGrid,
  },
]
